# Generated by Django 3.2.3 on 2021-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb_task2', '0002_auto_20210517_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
