# Generated by Django 3.2.3 on 2021-05-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jb_task2', '0005_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='login',
        ),
    ]
